/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesigclim;

/**
 *
 * @author INAMETCLIN-3
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButtonAWStempo = new javax.swing.JButton();
        Btnpesquisar = new javax.swing.JButton();
        btnsairdosistema = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jMenuEstacao = new javax.swing.JMenuItem();
        jMenuUsuario = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenusair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuelementosdurante24h = new javax.swing.JMenuItem();
        jMenuelementosdurantemes = new javax.swing.JMenuItem();
        jMenuelementosnumdia = new javax.swing.JMenuItem();
        jMenutemperatura = new javax.swing.JMenuItem();
        jMenuDadosemAltitude = new javax.swing.JMenuItem();
        jMenunebulosidadeetempo = new javax.swing.JMenuItem();
        jMenuPressaoHumidade = new javax.swing.JMenuItem();
        jMenuVisibilidadeEstadosoloPrecipitacao = new javax.swing.JMenuItem();
        jMenuPesquisa = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuBackup = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/box.png"))); // NOI18N
        jButton6.setText("Produtos");
        jButton6.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButtonAWStempo.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAWStempo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAWStempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/alarm32.png"))); // NOI18N
        jButtonAWStempo.setText("AWS Tempo Real ");
        jButtonAWStempo.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButtonAWStempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAWStempoActionPerformed(evt);
            }
        });

        Btnpesquisar.setBackground(new java.awt.Color(204, 204, 204));
        Btnpesquisar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Btnpesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/find.png"))); // NOI18N
        Btnpesquisar.setText("Pesquisar");
        Btnpesquisar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Btnpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnpesquisarActionPerformed(evt);
            }
        });

        btnsairdosistema.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnsairdosistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cancel.png"))); // NOI18N
        btnsairdosistema.setText("Sair do Sistema");
        btnsairdosistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsairdosistemaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnsairdosistema, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAWStempo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Btnpesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btnpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jButtonAWStempo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnsairdosistema, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(565, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SIGMET34.jpg"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(388, 388, 388)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(535, 535, 535))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 204, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenuBar1.setForeground(new java.awt.Color(102, 204, 255));
        jMenuBar1.setAutoscrolls(true);

        jMenu1.setText("Diversos");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem18.setText("Ficheiro Recente");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem18);

        jMenu9.setText("Opções");

        jMenuEstacao.setText("Configurar Estação");
        jMenuEstacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEstacaoActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuEstacao);

        jMenuUsuario.setText("Criar Usuario");
        jMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuUsuario);

        jMenu1.add(jMenu9);

        jMenuItem19.setText("Terminar sessão");
        jMenu1.add(jMenuItem19);

        jMenusair.setText("Sair");
        jMenusair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenusairActionPerformed(evt);
            }
        });
        jMenu1.add(jMenusair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Dados");

        jMenu10.setText("Inserir novos dados");

        jMenuelementosdurante24h.setText("De um elemento durante 24 horas");
        jMenuelementosdurante24h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuelementosdurante24hActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuelementosdurante24h);

        jMenuelementosdurantemes.setText("Dados de um elemento num mês");
        jMenuelementosdurantemes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuelementosdurantemesActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuelementosdurantemes);

        jMenuelementosnumdia.setText("Dados para certos elementos num dia ");
        jMenu10.add(jMenuelementosnumdia);

        jMenutemperatura.setText("Temperatura");
        jMenutemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenutemperaturaActionPerformed(evt);
            }
        });
        jMenu10.add(jMenutemperatura);

        jMenuDadosemAltitude.setText("Dados em altitude de vários elementos durante um dia ");
        jMenu10.add(jMenuDadosemAltitude);

        jMenunebulosidadeetempo.setText("Nebulosidade & Tempo");
        jMenunebulosidadeetempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenunebulosidadeetempoActionPerformed(evt);
            }
        });
        jMenu10.add(jMenunebulosidadeetempo);

        jMenuPressaoHumidade.setText("Pressao Atmosférica  & Humidade Relativa do Ar");
        jMenuPressaoHumidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPressaoHumidadeActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuPressaoHumidade);

        jMenuVisibilidadeEstadosoloPrecipitacao.setText("Visibilidade -Estado solo -Precipitacao");
        jMenuVisibilidadeEstadosoloPrecipitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVisibilidadeEstadosoloPrecipitacaoActionPerformed(evt);
            }
        });
        jMenu10.add(jMenuVisibilidadeEstadosoloPrecipitacao);

        jMenu2.add(jMenu10);

        jMenuPesquisa.setText("Verificar dados existentes");
        jMenuPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPesquisaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuPesquisa);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("    Acessórios     ");

        jMenuItem13.setText("Calculadora de pontos de Saturação e humidade relativa");
        jMenu3.add(jMenuItem13);

        jMenuItem14.setText("Criar XML Output");
        jMenu3.add(jMenuItem14);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Produtos        ");

        jMenuItem7.setText("Invetário");
        jMenu5.add(jMenuItem7);

        jMenuItem9.setText("Gráficos");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuItem10.setText("Clima");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuItem11.setText("Sumarios");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Administração   ");

        jMenuItem3.setText("Editar Usuario");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenuItem4.setText("Configuração de Dados");
        jMenu6.add(jMenuItem4);

        jMenuItem5.setText("Actualizar limites do elemento");
        jMenu6.add(jMenuItem5);

        jMenuBackup.setText("Backup");
        jMenuBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBackupActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuBackup);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Ferramentas      ");
        jMenuBar1.add(jMenu7);

        jMenu8.setText("Ajuda");
        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1152, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed

    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPesquisaActionPerformed
       Pesquisar Ps = new Pesquisar ();
      Ps.setLocationRelativeTo(null);
      Ps.setVisible(true);
    }//GEN-LAST:event_jMenuPesquisaActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuelementosdurantemesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuelementosdurantemesActionPerformed
     DadosdeumelementoduranteMes Dlm = new DadosdeumelementoduranteMes();
       Dlm.setLocationRelativeTo(null);
       Dlm.setVisible(true);
    }//GEN-LAST:event_jMenuelementosdurantemesActionPerformed

    private void jMenunebulosidadeetempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenunebulosidadeetempoActionPerformed
       NebulosidadeTempo NT = new NebulosidadeTempo();
       NT.setLocationRelativeTo(null);
       NT.setVisible(true);

    }//GEN-LAST:event_jMenunebulosidadeetempoActionPerformed

    private void btnsairdosistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsairdosistemaActionPerformed
       System.exit((0));
    }//GEN-LAST:event_btnsairdosistemaActionPerformed

    private void jMenuelementosdurante24hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuelementosdurante24hActionPerformed
      Deumelementodurante24horas Dlh = new  Deumelementodurante24horas();
      Dlh.setLocationRelativeTo(null);
       Dlh.setVisible(true);
    }//GEN-LAST:event_jMenuelementosdurante24hActionPerformed

    private void jMenutemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenutemperaturaActionPerformed
       Temperatura tmperatur = new Temperatura();
      tmperatur.setLocationRelativeTo(null);
       tmperatur.setVisible(true);
    }//GEN-LAST:event_jMenutemperaturaActionPerformed

    private void jMenuPressaoHumidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPressaoHumidadeActionPerformed
        PressaoHumidade PH = new PressaoHumidade();
      PH.setLocationRelativeTo(null);
       PH.setVisible(true);
    }//GEN-LAST:event_jMenuPressaoHumidadeActionPerformed

    private void jMenuVisibilidadeEstadosoloPrecipitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVisibilidadeEstadosoloPrecipitacaoActionPerformed
       visiblidadeelemento VEP = new visiblidadeelemento();
      VEP.setLocationRelativeTo(null);
       VEP.setVisible(true); 
    }//GEN-LAST:event_jMenuVisibilidadeEstadosoloPrecipitacaoActionPerformed

    private void jMenuBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBackupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBackupActionPerformed

    private void BtnpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnpesquisarActionPerformed
       Pesquisar pe = new Pesquisar();
       pe.setLocationRelativeTo(null);
      pe.setVisible(true);
    }//GEN-LAST:event_BtnpesquisarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonAWStempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAWStempoActionPerformed
          AwsTempoReal aws = new AwsTempoReal ();
       aws.setLocationRelativeTo(null);
     aws.setVisible(true);
    }//GEN-LAST:event_jButtonAWStempoActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed

    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenusairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenusairActionPerformed
        System.exit((0));
    }//GEN-LAST:event_jMenusairActionPerformed

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed
        CadastrodeUsuario cd = new CadastrodeUsuario ();
        cd.setLocationRelativeTo(null);
        cd.setVisible(true);
    }//GEN-LAST:event_jMenuUsuarioActionPerformed

    private void jMenuEstacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEstacaoActionPerformed
        CriarEstação CE = new CriarEstação();
        CE.setLocationRelativeTo(null);
        CE.setVisible(true);
    }//GEN-LAST:event_jMenuEstacaoActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnpesquisar;
    private javax.swing.JButton btnsairdosistema;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButtonAWStempo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuItem jMenuBackup;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuDadosemAltitude;
    private javax.swing.JMenuItem jMenuEstacao;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuPesquisa;
    private javax.swing.JMenuItem jMenuPressaoHumidade;
    private javax.swing.JMenuItem jMenuUsuario;
    private javax.swing.JMenuItem jMenuVisibilidadeEstadosoloPrecipitacao;
    private javax.swing.JMenuItem jMenuelementosdurante24h;
    private javax.swing.JMenuItem jMenuelementosdurantemes;
    private javax.swing.JMenuItem jMenuelementosnumdia;
    private javax.swing.JMenuItem jMenunebulosidadeetempo;
    private javax.swing.JMenuItem jMenusair;
    private javax.swing.JMenuItem jMenutemperatura;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
